<a href="https://colab.research.google.com/github/manipriyasaravanan30-spec/Project-/blob/main/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

marks =np.array([90, 85, 78, 92])

print(marks)

[90 85 78 92]


In [3]:
import numpy as np

arr= np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]
